name: Build Windows Installer

# Trigger workflow on push or pull request to main branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Java
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      # Step 3: Build the Maven project (creates fat JAR)
      - name: Build Maven Project
        run: mvn clean package

      # Step 4: Run jpackage to create Windows installer
      - name: Build Windows Installer
        run: |
          jpackage --input target/ `
                   --name ValorantSpinner `
                   --main-jar ValorantSpinner-1.0-SNAPSHOT.jar `
                   --main-class io.github.justinquach.ValorantSpinner `
                   --type exe `
                   --app-version 1.0
          
      # Step 5: Upload installer as build artifact
      - name: Upload Installer
        uses: actions/upload-artifact@v4
        with:
          name: ValorantSpinner-Windows-Installer
          path: ValorantSpinner.exe
